In [1]:
import pandas as pd

data1 =  pd.read_csv("SAMPLEIDS.csv")
print(f"{data1} \n \n")
data1.info()

    SNO    REGNO      NAME         DOB  GENDER      ADDRESS    M1    M2    M3  \
0     1  1220121      ARUN  2000-02-10    MALE    THANDALAM  82.0  81.0  90.0
1     2  1220122      BABU  1999-01-25    MALE  KANCHIPURAM  56.0  61.0  80.0
2     3  1220123    CHARAN  2000.09.21    MALE    THANDALAM   NaN  59.0  60.0
3     4  1220124      DEVA  2000-11-09    MALE   POONAMALEE  74.0  79.0  80.0
4     5  1220125     ESTER  2000-11-21  FEMALE      CHITHUR  92.0  95.0  96.0
5     6  1220126   FARHANA  1999-03-05  FEMALE    THANDALAM  91.0  88.0  90.0
6     7  1220127      GANI  2000-10-02    MALE  KANCHIPURAM  49.0  51.0  70.0
7     7  1220127      GANI  2000-10-02    MALE  KANCHIPURAM  49.0  51.0  70.0
8     8  1220128      HEMA  1999-01-25  FEMALE   POONAMALEE  95.0  96.0  90.0
9     9  1220129     INDRA  2000.09.21  FEMALE  KANCHIPURAM  64.0   NaN   NaN
10   10  1220130    JAHITH  2000-11-09    MALE    THANDALAM  34.0  45.0  50.0
11   11  1220131      KANI  2000-11-21  FEMALE      CHITHUR  96.0  95.0  96.0
12   12  1220132  LATHESSH  1999-03-05    MALE    THANDALAM   NaN  68.0  70.0
13   13  1220133      MANI  2000-10-02    MALE  KANCHIPURAM  71.0  76.0   NaN
14   14  1220134      NANI    20001109    MALE   POONAMALEE  79.0  77.0  80.0
15   15  1220135       NaN    19990125     NaN          NaN   NaN   NaN   NaN
16   16  1220136   PRATHAP    20000921    MALE  KANCHIPURAM  86.0  84.0  90.0
17   17  1220137     RAGHU    20001109    MALE   POONAMALEE  67.0  64.0  70.0
18   18  1220138     RATHI    20001121  FEMALE  KANCHIPURAM  81.0  86.0  90.0
19   19  1220139   SARVESH    19990305    MALE    THANDALAM  84.0  87.0   NaN
20   20  1220140  SANTHOSH    20001002    MALE  KANCHIPURAM  76.0  69.0  80.0

      M4  TOTAL         AVG
0    NaN    NaN         NaN
1   56.0  253.0   84.333333
2   70.0    NaN    0.000000
3   74.0  307.0  102.333333
4   92.0  375.0  125.000000
5   91.0  360.0  120.000000
6   49.0  219.0   73.000000
7   49.0  219.0   73.000000
8   95.0  376.0  125.333333
9   64.0    NaN    0.000000
10  34.0  163.0   54.333333
11  96.0  383.0  127.666667
12  70.0  208.0   69.333333
13  71.0    NaN    0.000000
14  79.0  315.0  105.000000
15   NaN    0.0    0.000000
16  86.0  346.0  115.333333
17   NaN  201.0   67.000000
18  81.0  338.0  112.666667
19  84.0    NaN    0.000000
20  76.0  301.0  100.333333


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SNO      21 non-null     int64
 1   REGNO    21 non-null     int64
 2   NAME     20 non-null     object
 3   DOB      21 non-null     object
 4   GENDER   20 non-null     object
 5   ADDRESS  20 non-null     object
 6   M1       18 non-null     float64
 7   M2       19 non-null     float64
 8   M3       17 non-null     float64
 9   M4       18 non-null     float64
 10  TOTAL    16 non-null     float64
 11  AVG      20 non-null     float64
dtypes: float64(6), int64(2), object(4)
memory usage: 2.1+ KB

In [2]:
data1.describe()
#gives mathematical summary of the data

,SNO,REGNO,M1,M2,M3,M4,TOTAL,AVG
count,21.000000,2.100000e+01,18.000000,19.000000,17.000000,18.000000,16.000000,20.000000
mean,10.333333,1.220130e+06,73.666667,74.315789,79.529412,73.166667,272.750000,72.733333
std,5.816643,5.816643e+00,17.580069,15.836149,13.010177,17.426315,102.048681,48.017127
min,1.000000,1.220121e+06,34.000000,45.000000,50.000000,34.000000,0.000000,0.000000
25%,6.000000,1.220126e+06,64.750000,62.500000,70.000000,65.500000,216.250000,40.750000
50%,10.000000,1.220130e+06,77.500000,77.000000,80.000000,75.000000,304.000000,78.666667
75%,15.000000,1.220135e+06,85.500000,86.500000,90.000000,85.500000,349.500000,113.333333
max,20.000000,1.220140e+06,96.000000,96.000000,96.000000,96.000000,383.000000,127.666667

In [3]:
data1.isnull()

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,False,False,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,True,True,False,True,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True,False,False,False,False,False
13,False,False,False,False,False,False,False,False,True,False,True,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,True,False,True,True,True,True,True,True,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,True,False,True,False
20,False,False,False,False,False,False,False,False,False,False,False,False

In [4]:
#remove the rows and colms wt null values
#def rows
data1.dropna(axis=1)
#will modify the OG data
#all col wt null val is del

    SNO    REGNO         DOB
0     1  1220121  2000-02-10
1     2  1220122  1999-01-25
2     3  1220123  2000.09.21
3     4  1220124  2000-11-09
4     5  1220125  2000-11-21
5     6  1220126  1999-03-05
6     7  1220127  2000-10-02
7     7  1220127  2000-10-02
8     8  1220128  1999-01-25
9     9  1220129  2000.09.21
10   10  1220130  2000-11-09
11   11  1220131  2000-11-21
12   12  1220132  1999-03-05
13   13  1220133  2000-10-02
14   14  1220134    20001109
15   15  1220135    19990125
16   16  1220136    20000921
17   17  1220137    20001109
18   18  1220138    20001121
19   19  1220139    19990305
20   20  1220140    20001002

In [5]:
data1.fillna("Null")

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,1,1220121,ARUN,2000-02-10,MALE,THANDALAM,82.0,81.0,90.0,Null,Null,Null
1,2,1220122,BABU,1999-01-25,MALE,KANCHIPURAM,56.0,61.0,80.0,56.0,253.0,84.333333
2,3,1220123,CHARAN,2000.09.21,MALE,THANDALAM,Null,59.0,60.0,70.0,Null,0.0
3,4,1220124,DEVA,2000-11-09,MALE,POONAMALEE,74.0,79.0,80.0,74.0,307.0,102.333333
4,5,1220125,ESTER,2000-11-21,FEMALE,CHITHUR,92.0,95.0,96.0,92.0,375.0,125.0
5,6,1220126,FARHANA,1999-03-05,FEMALE,THANDALAM,91.0,88.0,90.0,91.0,360.0,120.0
6,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.0
7,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.0
8,8,1220128,HEMA,1999-01-25,FEMALE,POONAMALEE,95.0,96.0,90.0,95.0,376.0,125.333333
9,9,1220129,INDRA,2000.09.21,FEMALE,KANCHIPURAM,64.0,Null,Null,64.0,Null,0.0
10,10,1220130,JAHITH,2000-11-09,MALE,THANDALAM,34.0,45.0,50.0,34.0,163.0,54.333333
11,11,1220131,KANI,2000-11-21,FEMALE,CHITHUR,96.0,95.0,96.0,96.0,383.0,127.666667
12,12,1220132,LATHESSH,1999-03-05,MALE,THANDALAM,Null,68.0,70.0,70.0,208.0,69.333333
13,13,1220133,MANI,2000-10-02,MALE,KANCHIPURAM,71.0,76.0,Null,71.0,Null,0.0
14,14,1220134,NANI,20001109,MALE,POONAMALEE,79.0,77.0,80.0,79.0,315.0,105.0
15,15,1220135,Null,19990125,Null,Null,Null,Null,Null,Null,0.0,0.0
16,16,1220136,PRATHAP,20000921,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,346.0,115.333333
17,17,1220137,RAGHU,20001109,MALE,POONAMALEE,67.0,64.0,70.0,Null,201.0,67.0
18,18,1220138,RATHI,20001121,FEMALE,KANCHIPURAM,81.0,86.0,90.0,81.0,338.0,112.666667
19,19,1220139,SARVESH,19990305,MALE,THANDALAM,84.0,87.0,Null,84.0,Null,0.0
20,20,1220140,SANTHOSH,20001002,MALE,KANCHIPURAM,76.0,69.0,80.0,76.0,301.0,100.333333

In [6]:
data1.bfill()

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,1,1220121,ARUN,2000-02-10,MALE,THANDALAM,82.0,81.0,90.0,56.0,253.0,84.333333
1,2,1220122,BABU,1999-01-25,MALE,KANCHIPURAM,56.0,61.0,80.0,56.0,253.0,84.333333
2,3,1220123,CHARAN,2000.09.21,MALE,THANDALAM,74.0,59.0,60.0,70.0,307.0,0.000000
3,4,1220124,DEVA,2000-11-09,MALE,POONAMALEE,74.0,79.0,80.0,74.0,307.0,102.333333
4,5,1220125,ESTER,2000-11-21,FEMALE,CHITHUR,92.0,95.0,96.0,92.0,375.0,125.000000
5,6,1220126,FARHANA,1999-03-05,FEMALE,THANDALAM,91.0,88.0,90.0,91.0,360.0,120.000000
6,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
7,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
8,8,1220128,HEMA,1999-01-25,FEMALE,POONAMALEE,95.0,96.0,90.0,95.0,376.0,125.333333
9,9,1220129,INDRA,2000.09.21,FEMALE,KANCHIPURAM,64.0,45.0,50.0,64.0,163.0,0.000000
10,10,1220130,JAHITH,2000-11-09,MALE,THANDALAM,34.0,45.0,50.0,34.0,163.0,54.333333
11,11,1220131,KANI,2000-11-21,FEMALE,CHITHUR,96.0,95.0,96.0,96.0,383.0,127.666667
12,12,1220132,LATHESSH,1999-03-05,MALE,THANDALAM,71.0,68.0,70.0,70.0,208.0,69.333333
13,13,1220133,MANI,2000-10-02,MALE,KANCHIPURAM,71.0,76.0,80.0,71.0,315.0,0.000000
14,14,1220134,NANI,20001109,MALE,POONAMALEE,79.0,77.0,80.0,79.0,315.0,105.000000
15,15,1220135,PRATHAP,19990125,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,0.0,0.000000
16,16,1220136,PRATHAP,20000921,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,346.0,115.333333
17,17,1220137,RAGHU,20001109,MALE,POONAMALEE,67.0,64.0,70.0,81.0,201.0,67.000000
18,18,1220138,RATHI,20001121,FEMALE,KANCHIPURAM,81.0,86.0,90.0,81.0,338.0,112.666667
19,19,1220139,SARVESH,19990305,MALE,THANDALAM,84.0,87.0,80.0,84.0,301.0,0.000000
20,20,1220140,SANTHOSH,20001002,MALE,KANCHIPURAM,76.0,69.0,80.0,76.0,301.0,100.333333

In [7]:
data1.ffill()

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,1,1220121,ARUN,2000-02-10,MALE,THANDALAM,82.0,81.0,90.0,NaN,NaN,NaN
1,2,1220122,BABU,1999-01-25,MALE,KANCHIPURAM,56.0,61.0,80.0,56.0,253.0,84.333333
2,3,1220123,CHARAN,2000.09.21,MALE,THANDALAM,56.0,59.0,60.0,70.0,253.0,0.000000
3,4,1220124,DEVA,2000-11-09,MALE,POONAMALEE,74.0,79.0,80.0,74.0,307.0,102.333333
4,5,1220125,ESTER,2000-11-21,FEMALE,CHITHUR,92.0,95.0,96.0,92.0,375.0,125.000000
5,6,1220126,FARHANA,1999-03-05,FEMALE,THANDALAM,91.0,88.0,90.0,91.0,360.0,120.000000
6,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
7,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
8,8,1220128,HEMA,1999-01-25,FEMALE,POONAMALEE,95.0,96.0,90.0,95.0,376.0,125.333333
9,9,1220129,INDRA,2000.09.21,FEMALE,KANCHIPURAM,64.0,96.0,90.0,64.0,376.0,0.000000
10,10,1220130,JAHITH,2000-11-09,MALE,THANDALAM,34.0,45.0,50.0,34.0,163.0,54.333333
11,11,1220131,KANI,2000-11-21,FEMALE,CHITHUR,96.0,95.0,96.0,96.0,383.0,127.666667
12,12,1220132,LATHESSH,1999-03-05,MALE,THANDALAM,96.0,68.0,70.0,70.0,208.0,69.333333
13,13,1220133,MANI,2000-10-02,MALE,KANCHIPURAM,71.0,76.0,70.0,71.0,208.0,0.000000
14,14,1220134,NANI,20001109,MALE,POONAMALEE,79.0,77.0,80.0,79.0,315.0,105.000000
15,15,1220135,NANI,19990125,MALE,POONAMALEE,79.0,77.0,80.0,79.0,0.0,0.000000
16,16,1220136,PRATHAP,20000921,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,346.0,115.333333
17,17,1220137,RAGHU,20001109,MALE,POONAMALEE,67.0,64.0,70.0,86.0,201.0,67.000000
18,18,1220138,RATHI,20001121,FEMALE,KANCHIPURAM,81.0,86.0,90.0,81.0,338.0,112.666667
19,19,1220139,SARVESH,19990305,MALE,THANDALAM,84.0,87.0,90.0,84.0,338.0,0.000000
20,20,1220140,SANTHOSH,20001002,MALE,KANCHIPURAM,76.0,69.0,80.0,76.0,301.0,100.333333

In [8]:
data1['TOTAL'].fillna(value=data1['TOTAL'].mean(),inplace=True)
print(data1)

    SNO    REGNO      NAME         DOB  GENDER      ADDRESS    M1    M2    M3  \
0     1  1220121      ARUN  2000-02-10    MALE    THANDALAM  82.0  81.0  90.0
1     2  1220122      BABU  1999-01-25    MALE  KANCHIPURAM  56.0  61.0  80.0
2     3  1220123    CHARAN  2000.09.21    MALE    THANDALAM   NaN  59.0  60.0
3     4  1220124      DEVA  2000-11-09    MALE   POONAMALEE  74.0  79.0  80.0
4     5  1220125     ESTER  2000-11-21  FEMALE      CHITHUR  92.0  95.0  96.0
5     6  1220126   FARHANA  1999-03-05  FEMALE    THANDALAM  91.0  88.0  90.0
6     7  1220127      GANI  2000-10-02    MALE  KANCHIPURAM  49.0  51.0  70.0
7     7  1220127      GANI  2000-10-02    MALE  KANCHIPURAM  49.0  51.0  70.0
8     8  1220128      HEMA  1999-01-25  FEMALE   POONAMALEE  95.0  96.0  90.0
9     9  1220129     INDRA  2000.09.21  FEMALE  KANCHIPURAM  64.0   NaN   NaN
10   10  1220130    JAHITH  2000-11-09    MALE    THANDALAM  34.0  45.0  50.0
11   11  1220131      KANI  2000-11-21  FEMALE      CHITHUR  96.0  95.0  96.0
12   12  1220132  LATHESSH  1999-03-05    MALE    THANDALAM   NaN  68.0  70.0
13   13  1220133      MANI  2000-10-02    MALE  KANCHIPURAM  71.0  76.0   NaN
14   14  1220134      NANI    20001109    MALE   POONAMALEE  79.0  77.0  80.0
15   15  1220135       NaN    19990125     NaN          NaN   NaN   NaN   NaN
16   16  1220136   PRATHAP    20000921    MALE  KANCHIPURAM  86.0  84.0  90.0
17   17  1220137     RAGHU    20001109    MALE   POONAMALEE  67.0  64.0  70.0
18   18  1220138     RATHI    20001121  FEMALE  KANCHIPURAM  81.0  86.0  90.0
19   19  1220139   SARVESH    19990305    MALE    THANDALAM  84.0  87.0   NaN
20   20  1220140  SANTHOSH    20001002    MALE  KANCHIPURAM  76.0  69.0  80.0

      M4   TOTAL         AVG
0    NaN  272.75         NaN
1   56.0  253.00   84.333333
2   70.0  272.75    0.000000
3   74.0  307.00  102.333333
4   92.0  375.00  125.000000
5   91.0  360.00  120.000000
6   49.0  219.00   73.000000
7   49.0  219.00   73.000000
8   95.0  376.00  125.333333
9   64.0  272.75    0.000000
10  34.0  163.00   54.333333
11  96.0  383.00  127.666667
12  70.0  208.00   69.333333
13  71.0  272.75    0.000000
14  79.0  315.00  105.000000
15   NaN    0.00    0.000000
16  86.0  346.00  115.333333
17   NaN  201.00   67.000000
18  81.0  338.00  112.666667
19  84.0  272.75    0.000000
20  76.0  301.00  100.333333

In [10]:
data2= pd.read_csv("Loan_data.csv")
print(f"{data2} \n \n")
data2.info()

      Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No
1    LP001022   Male     Yes          1      Graduate            No
2    LP001031   Male     Yes          2      Graduate            No
3    LP001035   Male     Yes          2      Graduate            No
4    LP001051   Male      No          0  Not Graduate            No
..        ...    ...     ...        ...           ...           ...
362  LP002971   Male     Yes         3+  Not Graduate           Yes
363  LP002975   Male     Yes          0      Graduate            No
364  LP002980   Male      No          0      Graduate            No
365  LP002986   Male     Yes          0      Graduate            No
366  LP002989   Male      No          0      Graduate           Yes

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0
1               3076               1500       126.0             360.0
2               5000               1800       208.0             360.0
3               2340               2546       100.0             360.0
4               3276                  0        78.0             360.0
..               ...                ...         ...               ...
362             4009               1777       113.0             360.0
363             4158                709       115.0             360.0
364             3250               1993       126.0             360.0
365             5000               2393       158.0             360.0
366             9200                  0        98.0             180.0

     Credit_History Property_Area
0               1.0         Urban
1               1.0         Urban
2               1.0         Urban
3               NaN         Urban
4               1.0         Urban
..              ...           ...
362             1.0         Urban
363             1.0         Urban
364             NaN     Semiurban
365             1.0         Rural
366             1.0         Rural

[367 rows x 12 columns]


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             356 non-null    object
 2   Married            367 non-null    object
 3   Dependents         357 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      344 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

In [11]:
data2.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,367.000000,367.000000,362.000000,361.000000,338.000000
mean,4805.599455,1569.577657,136.132597,342.537396,0.825444
std,4910.685399,2334.232099,61.366652,65.156643,0.380150
min,0.000000,0.000000,28.000000,6.000000,0.000000
25%,2864.000000,0.000000,100.250000,360.000000,1.000000
50%,3786.000000,1025.000000,125.000000,360.000000,1.000000
75%,5060.000000,2430.500000,158.000000,360.000000,1.000000
max,72529.000000,24000.000000,550.000000,480.000000,1.000000

In [12]:
data2.isnull()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
362,False,False,False,False,False,False,False,False,False,False,False,False
363,False,False,False,False,False,False,False,False,False,False,False,False
364,False,False,False,False,False,False,False,False,False,False,True,False
365,False,False,False,False,False,False,False,False,False,False,False,False
366,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
data2.dropna(axis=1,inplace=True)
print(data2)

      Loan_ID Married     Education  ApplicantIncome  CoapplicantIncome  \
0    LP001015     Yes      Graduate             5720                  0
1    LP001022     Yes      Graduate             3076               1500
2    LP001031     Yes      Graduate             5000               1800
3    LP001035     Yes      Graduate             2340               2546
4    LP001051      No  Not Graduate             3276                  0
..        ...     ...           ...              ...                ...
362  LP002971     Yes  Not Graduate             4009               1777
363  LP002975     Yes      Graduate             4158                709
364  LP002980      No      Graduate             3250               1993
365  LP002986     Yes      Graduate             5000               2393
366  LP002989      No      Graduate             9200                  0

    Property_Area
0           Urban
1           Urban
2           Urban
3           Urban
4           Urban
..            ...
362         Urban
363         Urban
364     Semiurban
365         Rural
366         Rural

[367 rows x 6 columns]

In [14]:
data2.fillna("Null")

,Loan_ID,Married,Education,ApplicantIncome,CoapplicantIncome,Property_Area
0,LP001015,Yes,Graduate,5720,0,Urban
1,LP001022,Yes,Graduate,3076,1500,Urban
2,LP001031,Yes,Graduate,5000,1800,Urban
3,LP001035,Yes,Graduate,2340,2546,Urban
4,LP001051,No,Not Graduate,3276,0,Urban
...,...,...,...,...,...,...
362,LP002971,Yes,Not Graduate,4009,1777,Urban
363,LP002975,Yes,Graduate,4158,709,Urban
364,LP002980,No,Graduate,3250,1993,Semiurban
365,LP002986,Yes,Graduate,5000,2393,Rural
366,LP002989,No,Graduate,9200,0,Rural

In [17]:
data2.ffill() 
data2.bfill()

,Loan_ID,Married,Education,ApplicantIncome,CoapplicantIncome,Property_Area
0,LP001015,Yes,Graduate,5720,0,Urban
1,LP001022,Yes,Graduate,3076,1500,Urban
2,LP001031,Yes,Graduate,5000,1800,Urban
3,LP001035,Yes,Graduate,2340,2546,Urban
4,LP001051,No,Not Graduate,3276,0,Urban
...,...,...,...,...,...,...
362,LP002971,Yes,Not Graduate,4009,1777,Urban
363,LP002975,Yes,Graduate,4158,709,Urban
364,LP002980,No,Graduate,3250,1993,Semiurban
365,LP002986,Yes,Graduate,5000,2393,Rural
366,LP002989,No,Graduate,9200,0,Rural

In [18]:
data3 = pd.read_csv("Data_set.csv")
print(data3)

                   show_name      country  num_episodes             aired_on  \
0                        NaN  South Korea            16     Friday, Saturday
1                        NaN  South Korea            16     Friday, Saturday
2     Descendants of the Sun  South Korea            16  Wednesday, Thursday
3          Boys Over Flowers  South Korea            25      Monday, Tuesday
4                          W  South Korea            16  Wednesday, Thursday
..                       ...          ...           ...                  ...
95  Shut Up: Flower Boy Band  South Korea            16      Monday, Tuesday
96                     Blood  South Korea            20      Monday, Tuesday
97        Chicago Typewriter  South Korea            16     Friday, Saturday
98      Sungkyunkwan Scandal  South Korea            20      Monday, Tuesday
99                  Vagabond  South Korea            16     Friday, Saturday

   original_network  rating  current_overall_rank  lifetime_popularity_rank  \
0               tvN     8.9                  33.0                         1
1              jTBC     8.7                  89.0                         2
2              KBS2     8.7                  77.0                         3
3              KBS2     7.7                2249.0                         4
4               MBC     8.5                 201.0                         5
..              ...     ...                   ...                       ...
95              tvN     8.1                 806.0                        99
96             KBS2     7.4                3271.0                       100
97              tvN     8.8                  51.0                       101
98             KBS2     8.2                 605.0                       102
99     SBS, Netflix     8.5                 238.0                       103

    watchers
0   111706.0
1   100950.0
2    96318.0
3    94228.0
4    92121.0
..       ...
95   34668.0
96   34666.0
97       NaN
98   34615.0
99   34523.0

[100 rows x 9 columns]

In [19]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   show_name                 96 non-null     object
 1   country                   100 non-null    object
 2   num_episodes              100 non-null    int64
 3   aired_on                  99 non-null     object
 4   original_network          99 non-null     object
 5   rating                    96 non-null     float64
 6   current_overall_rank      97 non-null     float64
 7   lifetime_popularity_rank  100 non-null    int64
 8   watchers                  97 non-null     float64
dtypes: float64(3), int64(2), object(4)
memory usage: 7.2+ KB

In [22]:
data3.describe()

,num_episodes,rating,current_overall_rank,lifetime_popularity_rank,watchers
count,100.000000,96.000000,97.000000,100.000000,97.000000
mean,18.980000,8.293750,731.247423,51.650000,52994.907216
std,6.846041,0.424714,857.597007,30.133164,17551.028458
min,8.000000,7.300000,2.000000,1.000000,34523.000000
25%,16.000000,8.100000,194.000000,25.750000,39545.000000
50%,16.000000,8.300000,441.000000,51.500000,46963.000000
75%,20.000000,8.600000,806.000000,77.250000,63140.000000
max,50.000000,9.100000,3788.000000,103.000000,111706.000000

In [23]:
data3.isnull()

,show_name,country,num_episodes,aired_on,original_network,rating,current_overall_rank,lifetime_popularity_rank,watchers
0,True,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,True
98,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False

In [24]:
data3.fillna("Null")

,show_name,country,num_episodes,aired_on,original_network,rating,current_overall_rank,lifetime_popularity_rank,watchers
0,Null,South Korea,16,"Friday, Saturday",tvN,8.9,33.0,1,111706.0
1,Null,South Korea,16,"Friday, Saturday",jTBC,8.7,89.0,2,100950.0
2,Descendants of the Sun,South Korea,16,"Wednesday, Thursday",KBS2,8.7,77.0,3,96318.0
3,Boys Over Flowers,South Korea,25,"Monday, Tuesday",KBS2,7.7,2249.0,4,94228.0
4,W,South Korea,16,"Wednesday, Thursday",MBC,8.5,201.0,5,92121.0
...,...,...,...,...,...,...,...,...,...
95,Shut Up: Flower Boy Band,South Korea,16,"Monday, Tuesday",tvN,8.1,806.0,99,34668.0
96,Blood,South Korea,20,"Monday, Tuesday",KBS2,7.4,3271.0,100,34666.0
97,Chicago Typewriter,South Korea,16,"Friday, Saturday",tvN,8.8,51.0,101,Null
98,Sungkyunkwan Scandal,South Korea,20,"Monday, Tuesday",KBS2,8.2,605.0,102,34615.0
99,Vagabond,South Korea,16,"Friday, Saturday","SBS, Netflix",8.5,238.0,103,34523.0

In [25]:
data3.ffill()

,show_name,country,num_episodes,aired_on,original_network,rating,current_overall_rank,lifetime_popularity_rank,watchers
0,NaN,South Korea,16,"Friday, Saturday",tvN,8.9,33.0,1,111706.0
1,NaN,South Korea,16,"Friday, Saturday",jTBC,8.7,89.0,2,100950.0
2,Descendants of the Sun,South Korea,16,"Wednesday, Thursday",KBS2,8.7,77.0,3,96318.0
3,Boys Over Flowers,South Korea,25,"Monday, Tuesday",KBS2,7.7,2249.0,4,94228.0
4,W,South Korea,16,"Wednesday, Thursday",MBC,8.5,201.0,5,92121.0
...,...,...,...,...,...,...,...,...,...
95,Shut Up: Flower Boy Band,South Korea,16,"Monday, Tuesday",tvN,8.1,806.0,99,34668.0
96,Blood,South Korea,20,"Monday, Tuesday",KBS2,7.4,3271.0,100,34666.0
97,Chicago Typewriter,South Korea,16,"Friday, Saturday",tvN,8.8,51.0,101,34666.0
98,Sungkyunkwan Scandal,South Korea,20,"Monday, Tuesday",KBS2,8.2,605.0,102,34615.0
99,Vagabond,South Korea,16,"Friday, Saturday","SBS, Netflix",8.5,238.0,103,34523.0

In [26]:
data3.bfill()

,show_name,country,num_episodes,aired_on,original_network,rating,current_overall_rank,lifetime_popularity_rank,watchers
0,Descendants of the Sun,South Korea,16,"Friday, Saturday",tvN,8.9,33.0,1,111706.0
1,Descendants of the Sun,South Korea,16,"Friday, Saturday",jTBC,8.7,89.0,2,100950.0
2,Descendants of the Sun,South Korea,16,"Wednesday, Thursday",KBS2,8.7,77.0,3,96318.0
3,Boys Over Flowers,South Korea,25,"Monday, Tuesday",KBS2,7.7,2249.0,4,94228.0
4,W,South Korea,16,"Wednesday, Thursday",MBC,8.5,201.0,5,92121.0
...,...,...,...,...,...,...,...,...,...
95,Shut Up: Flower Boy Band,South Korea,16,"Monday, Tuesday",tvN,8.1,806.0,99,34668.0
96,Blood,South Korea,20,"Monday, Tuesday",KBS2,7.4,3271.0,100,34666.0
97,Chicago Typewriter,South Korea,16,"Friday, Saturday",tvN,8.8,51.0,101,34615.0
98,Sungkyunkwan Scandal,South Korea,20,"Monday, Tuesday",KBS2,8.2,605.0,102,34615.0
99,Vagabond,South Korea,16,"Friday, Saturday","SBS, Netflix",8.5,238.0,103,34523.0

In [28]:
data3['watchers'].fillna(value=data3['watchers'].mean(),inplace=True)
print(data3)

                   show_name      country  num_episodes             aired_on  \
0                        NaN  South Korea            16     Friday, Saturday
1                        NaN  South Korea            16     Friday, Saturday
2     Descendants of the Sun  South Korea            16  Wednesday, Thursday
3          Boys Over Flowers  South Korea            25      Monday, Tuesday
4                          W  South Korea            16  Wednesday, Thursday
..                       ...          ...           ...                  ...
95  Shut Up: Flower Boy Band  South Korea            16      Monday, Tuesday
96                     Blood  South Korea            20      Monday, Tuesday
97        Chicago Typewriter  South Korea            16     Friday, Saturday
98      Sungkyunkwan Scandal  South Korea            20      Monday, Tuesday
99                  Vagabond  South Korea            16     Friday, Saturday

   original_network  rating  current_overall_rank  lifetime_popularity_rank  \
0               tvN     8.9                  33.0                         1
1              jTBC     8.7                  89.0                         2
2              KBS2     8.7                  77.0                         3
3              KBS2     7.7                2249.0                         4
4               MBC     8.5                 201.0                         5
..              ...     ...                   ...                       ...
95              tvN     8.1                 806.0                        99
96             KBS2     7.4                3271.0                       100
97              tvN     8.8                  51.0                       101
98             KBS2     8.2                 605.0                       102
99     SBS, Netflix     8.5                 238.0                       103

         watchers
0   111706.000000
1   100950.000000
2    96318.000000
3    94228.000000
4    92121.000000
..            ...
95   34668.000000
96   34666.000000
97   52994.907216
98   34615.000000
99   34523.000000

[100 rows x 9 columns]